## 예외 처리
* 코루틴에서 예외가 발생하면 부모로 전파할 뿐만 아니라 자식 코루틴들도 취소함
* 부모 코루틴이 취소되면 그의 자식 코루틴들도 취소되기 때문에 구조상 모든 코루틴이 취소되게 됨

### 코루틴 종료 멈추기
* 코루틴의 상호작용은 잡을 통해서 일어나기 때문에 try, catch문으로는 예외처리를 할 수 없음


#### SupervisorJob
* 자식에서 일어난 예외 무시
```kotlin
runBlocking {
    val scope = CoroutineScope(SupervisorJob())
    scope.launch {
        delay(1000)
        throw Error("Some error")
    }

    scope.launch {
        delay(2000)
        println("Will be printed")
    }

    delay(3000)
}
// Exception
// Will be printed
```

* 이렇게 하면 SupervisorJob이 제대로 전달되지 않음
```kotlin
runBlocking {
    launch(SupervisorJob()) {
        launch  {
            delay(1000)
            throw Error("Some error")
        }

        launch {
            delay(2000)
            println("호출되지 않는 코드")
        }
    }
}
// Job은 부모의 것을 상속받지 않는다
```

#### supervisorScope
* 다른 코루틴에서 발생한 예외 무시, 부모와의 연결을 유지한다는 점이 장점
```kotlin
runBlocking {
    supervisorScope {
        launch {
            delay(1000)
            throw Error("Some error")
        }

        launch {
            delay(2000)
            println("Will be printed")
        }
    }
    delay(1000)
    println("Done")
}

// Exception...
//Will be printed
(1초후)
// Done
```

* withContext(SupervisorJob())으로 대체할 수 없음


#### await()
* 코루틴이 예외를 던지면 await()함수도 예외를 던짐

### CancellationException 은 부모까지 전파되지 않음
* 현재 코루틴을 취소시킬 뿐

### 코루틴 예외 핸들러
* 예외를 다룰 때 기본행동을 정의할 때 사용
```kotlin
runBlcking {
    val handler = CoroutineExceptionHandler { ctx, exception ->
        println("Caught $exception")
    }
    val scope = CoroutineScope(SupervisorJob() + handler)
    scope.launch {
        delay(1000)
        throw Error("Some error")
    }

    scope.launch {
        delay(2000)
        println("Will be printed")
    }

    delay(3000)
}

// Caught java.lang.Error: Some error
// Will be printed
```