## 취소
* 호출한 코루틴은 첫 번째 중단점에서 잡을 끝냄
* 자식잡들 또한 취소됨. 단, 부모쪽으로는 영향이 가지 않음
* 취소된 잡은 새로운 코루틴의 부모가 될 수 없음.
* 취소시 Cancelling -> Cancelled 상태가 됨

### cancel & join
* cancel()함수는 말 그대로 코루틴을 cancel시키는 함수
* join도 같이 호출해줘야 의도대로 코루틴을 취소할 수 있음
```kotlin
suspend fun main() = coroutineScope {
    val job = launch {
        repeat(1000) { i->
            delay(100)
            Thread.sleep(100)
            println("Printing $i")
        }
    }

    delay(1000)
    job.cancel() 
    /** 
    cancel을 호출했지만 
    아래있는 println()은 cancel을 기다리지 않고 실행되기 때문에 
    race condition이 됨 -> job.join() 호출 필요 이유
    */
    println("Cancelled successfully")
}
```

```kotlin
job.cancel()
job.join()
-> job.cancelAndJoin() 이라는 함수 사용 가능
```

### 취소 작동 방식
* 취소 호출 후 첫 번째 중단점에서 **CancellationException** 예외를 던짐
```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        try {
            repeat(1000) { i ->
                delay(200)
                println("Printing $i")
            }
        } catch (e: CancellationException) {
            println(e)
            throw e
        }
    }
    delay(1100)
    job.cancelAndJoin()
    println("Cancelled successfully")
    delay(1000)
}
```
* 출력결과
    * Printing 0
    * Printing 1
    * Printing 2
    * Printing 3
    * Printing 4
    * JobCancellationException~~~ 
        * Printing $i 5번째 실행 후 6번째 실행 도중 cancelAndJoin()이 실행됐으므로 중단점인 delay(200) 에서 exception을 발생시킨다
    * Cancelled successfully

* 취소는 exception을 발생시키므로 파일, 데이터 베이스 닫기 등의 로직들은 finally 블록을 사용할 수 있음

### 취소 중 코루틴 한번 더 호출
```kotlin 
coroutineScope {
    val job = Job()
    launch(job) {
        try {
            delay(2000)
            println("Job is done")
        } finally {
            println("Finally")
            launch { // cancel 호출 이후 코루틴은 생성되지 않는다
                println("호출되지 않는 부분")
            }
            delay(1000)// cancel 호출 이후 코루틴은 생성되지 않는다 - 예외 발생
            println("호출되지 않는 부분")
        }
    }
    delay(1000)
    job.cancelAndJoin()
    println("Cancel done")
}
```

* 꼭 중단 함수를 취소 이후에 호출해야한다면 withContext(NonCancellable) 을 사용하면 됨
```kotlin 
coroutineScope {
    val job = Job()
    launch(job) {
        try {
            delay(2000)
            println("Job is done")
        } finally {
            println("Finally")
            withContext(NonCancellable) { // 취소되도 해당 코루틴은 정상 작동함
                delay(1000)
                println("cleanup done")
            }
        }
    }
    delay(1000)
    job.cancelAndJoin()
    println("Cancel done")
}
```
* 혹은 invokeOnCompletion 사용
```kotlin 
coroutineScope {
    val job = launch {
        delay(Random.nextLong(2400))
        println("Finished")
    }
    job.invokeOnCompletion { exception: Trowable? -> // 취소되지 않았다면 exception은 null
        println("Finished")
    }
    delay(1000)
    job.cancelAndJoin()
}
```

### 중단할 수 없는 코루틴 취소하기
* 중단점이 없는 코루틴의 경우 cancel()을 호출해도 코루틴이 취소되지 않는다
* 주기적으로 yield() 호출하기
    * yield는 코루틴을 중단하고 즉시 재실행함 -> 중단점을 하나 추가하는 셈

* Job의 상태 추적하기
    * `isActive`를 활용해 active가 아닐 때 Job을 취소시킬 수 있음
    * active상태가 아니면 CancellationException을 던지는 `ensureActive()`함수를 사용할 수 있음